name             'node_app'
maintainer       'Kiddo Labs'
maintainer_email 'rafael@kiddolabs.com'
license          'MIT'
description      'Installs/Configures the node application developed by KiddoLabs in nginx and pm2'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.1'
depends          'nginx'
depends          'magic_shell'
depends          'nodejs'
